-- =====================================================================
--  MoviRuta · esquema para Supabase (PostgreSQL 15+)
--  Mismas tablas, columnas, llaves foráneas y nombres de restricciones que moviruta.sql (MySQL), para que
--  la API funcione igual con las dos bases y database/sincronizar.php pueda copiar Supabase → MySQL.
--  Ejecutar en Supabase → SQL Editor y después supabase_datos_demo.sql. ¡Borra las tablas si ya existen!
--  La API se conecta con el usuario postgres; las tablas no quedan expuestas a la API pública de Supabase.
-- =====================================================================

DROP VIEW IF EXISTS vista_fallas_abiertas, vista_viajes_en_curso, vista_rutas;
DROP TABLE IF EXISTS sesion, historial_consulta, falla_vehiculo, reporte_accidente, viaje, recorrido_punto, ruta_parada,
    ruta, parada, vehiculo, chofer, linea_transporte, usuario, estado_falla, tipo_falla, estado_reporte, estado_viaje,
    estado_servicio, sentido_ruta, rol CASCADE;

-- ---------------------------------------------------------------------
--  Catálogos
-- ---------------------------------------------------------------------

CREATE TABLE rol (
    clave       VARCHAR(20)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(40)  NOT NULL CONSTRAINT uq_rol_nombre UNIQUE
);

CREATE TABLE sentido_ruta (
    clave       VARCHAR(10)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(30)  NOT NULL
);

CREATE TABLE estado_servicio (
    clave       VARCHAR(20)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(40)  NOT NULL
);

CREATE TABLE estado_viaje (
    clave       VARCHAR(15)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(30)  NOT NULL
);

CREATE TABLE estado_reporte (
    clave       VARCHAR(15)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(30)  NOT NULL
);

CREATE TABLE tipo_falla (
    clave       VARCHAR(20)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(60)  NOT NULL
);

CREATE TABLE estado_falla (
    clave       VARCHAR(15)  NOT NULL PRIMARY KEY,
    nombre      VARCHAR(30)  NOT NULL
);

INSERT INTO rol (clave, nombre) VALUES
    ('pasajero', 'Pasajero'), ('chofer', 'Chofer'), ('dueno', 'Dueño de línea'), ('admin', 'Administrador general');
INSERT INTO sentido_ruta (clave, nombre) VALUES
    ('ida', 'Ida'), ('vuelta', 'Vuelta'), ('circular', 'Circuito');
INSERT INTO estado_servicio (clave, nombre) VALUES
    ('normal', 'Operando con normalidad'), ('con_retrasos', 'Servicio con retrasos'), ('suspendida', 'Servicio suspendido');
INSERT INTO estado_viaje (clave, nombre) VALUES
    ('en_curso', 'En curso'), ('finalizado', 'Finalizado');
INSERT INTO estado_reporte (clave, nombre) VALUES
    ('nuevo', 'Nuevo'), ('revisado', 'Revisado');
INSERT INTO tipo_falla (clave, nombre) VALUES
    ('llanta', 'Llanta ponchada o dañada'), ('clima', 'Aire acondicionado / clima'), ('frenos', 'Frenos'),
    ('motor', 'Motor o transmisión'), ('electrico', 'Luces o sistema eléctrico'), ('puertas', 'Puertas o ventanas'),
    ('rampa', 'Rampa o equipo de accesibilidad'), ('gps', 'GPS o dispositivo de ubicación'),
    ('interior', 'Asientos, carrocería o interior'), ('otro', 'Otra falla');
INSERT INTO estado_falla (clave, nombre) VALUES
    ('pendiente', 'Pendiente'), ('en_reparacion', 'En reparación'), ('resuelta', 'Resuelta');

-- ---------------------------------------------------------------------
--  Usuarios y líneas
-- ---------------------------------------------------------------------

CREATE TABLE usuario (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol             VARCHAR(20)  NOT NULL,
    nombre          VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    activo          SMALLINT     NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
    ultimo_acceso   TIMESTAMPTZ  NULL,
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol) REFERENCES rol (clave) ON UPDATE CASCADE
);
CREATE INDEX ix_usuario_rol ON usuario (rol);

CREATE TABLE linea_transporte (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL,
    descripcion     VARCHAR(255) NULL,
    telefono        VARCHAR(30)  NULL,
    dueno_id        INTEGER      NULL,
    activa          SMALLINT     NOT NULL DEFAULT 1 CHECK (activa IN (0, 1)),
    CONSTRAINT uq_linea_nombre UNIQUE (nombre),
    CONSTRAINT fk_linea_dueno FOREIGN KEY (dueno_id) REFERENCES usuario (id) ON DELETE SET NULL
);
CREATE INDEX ix_linea_dueno ON linea_transporte (dueno_id);

CREATE TABLE chofer (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      INTEGER      NOT NULL,
    linea_id        INTEGER      NOT NULL,
    numero_licencia VARCHAR(30)  NOT NULL,
    telefono        VARCHAR(30)  NULL,
    activo          SMALLINT     NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
    CONSTRAINT uq_chofer_usuario UNIQUE (usuario_id),
    CONSTRAINT uq_chofer_licencia UNIQUE (numero_licencia),
    CONSTRAINT fk_chofer_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT fk_chofer_linea   FOREIGN KEY (linea_id)   REFERENCES linea_transporte (id)
);
CREATE INDEX ix_chofer_linea ON chofer (linea_id);

CREATE TABLE vehiculo (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    linea_id        INTEGER      NOT NULL,
    numero_unidad   VARCHAR(20)  NOT NULL,
    placa           VARCHAR(15)  NOT NULL,
    modelo          VARCHAR(80)  NULL,
    capacidad       SMALLINT     NULL CHECK (capacidad >= 0),
    cuenta_con_gps  SMALLINT     NOT NULL DEFAULT 0 CHECK (cuenta_con_gps IN (0, 1)),
    climatizado     SMALLINT     NOT NULL DEFAULT 0 CHECK (climatizado IN (0, 1)),
    tv_a_bordo      SMALLINT     NOT NULL DEFAULT 0 CHECK (tv_a_bordo IN (0, 1)),
    accesible       SMALLINT     NOT NULL DEFAULT 0 CHECK (accesible IN (0, 1)),
    activo          SMALLINT     NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
    CONSTRAINT uq_vehiculo_placa UNIQUE (placa),
    CONSTRAINT uq_vehiculo_unidad UNIQUE (linea_id, numero_unidad),
    CONSTRAINT fk_vehiculo_linea FOREIGN KEY (linea_id) REFERENCES linea_transporte (id)
);

-- ---------------------------------------------------------------------
--  Paradas y rutas
-- ---------------------------------------------------------------------

CREATE TABLE parada (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(10)  NULL,
    nombre          VARCHAR(120) NOT NULL,
    referencia      VARCHAR(255) NULL,
    latitud         NUMERIC(9,6) NOT NULL,
    longitud        NUMERIC(9,6) NOT NULL,
    activa          SMALLINT     NOT NULL DEFAULT 1 CHECK (activa IN (0, 1)),
    CONSTRAINT uq_parada_codigo UNIQUE (codigo)
);
COMMENT ON COLUMN parada.codigo IS 'Código de poste, p. ej. 108 (se muestra como #108)';

CREATE TABLE ruta (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    linea_id                INTEGER      NOT NULL,
    codigo                  VARCHAR(10)  NOT NULL,
    nombre                  VARCHAR(120) NOT NULL,
    origen                  VARCHAR(120) NOT NULL,
    destino                 VARCHAR(120) NOT NULL,
    sentido                 VARCHAR(10)  NOT NULL,
    color                   CHAR(7)      NOT NULL,
    tarifa                  NUMERIC(7,2) NULL,
    velocidad_promedio_kmh  NUMERIC(5,2) NOT NULL,
    estado_servicio         VARCHAR(20)  NOT NULL DEFAULT 'normal',
    aviso                   VARCHAR(255) NULL,
    activa                  SMALLINT     NOT NULL DEFAULT 1 CHECK (activa IN (0, 1)),
    CONSTRAINT uq_ruta_codigo UNIQUE (linea_id, codigo, sentido),
    CONSTRAINT fk_ruta_linea   FOREIGN KEY (linea_id)        REFERENCES linea_transporte (id),
    CONSTRAINT fk_ruta_sentido FOREIGN KEY (sentido)         REFERENCES sentido_ruta (clave) ON UPDATE CASCADE,
    CONSTRAINT fk_ruta_estado  FOREIGN KEY (estado_servicio) REFERENCES estado_servicio (clave) ON UPDATE CASCADE
);
CREATE INDEX ix_ruta_sentido ON ruta (sentido);
CREATE INDEX ix_ruta_estado ON ruta (estado_servicio);
COMMENT ON COLUMN ruta.codigo IS 'Número de ruta visible, p. ej. 1, P1';

-- Paradas de cada ruta en el orden del recorrido (una parada puede repetirse, p. ej. en circuitos).
CREATE TABLE ruta_parada (
    ruta_id     INTEGER  NOT NULL,
    orden       SMALLINT NOT NULL CHECK (orden > 0),
    parada_id   INTEGER  NOT NULL,
    PRIMARY KEY (ruta_id, orden),
    CONSTRAINT fk_ruta_parada_ruta   FOREIGN KEY (ruta_id)   REFERENCES ruta (id) ON DELETE CASCADE,
    CONSTRAINT fk_ruta_parada_parada FOREIGN KEY (parada_id) REFERENCES parada (id)
);
CREATE INDEX ix_ruta_parada_parada ON ruta_parada (parada_id);

-- Trazado de cada ruta sobre el mapa (puntos en orden).
CREATE TABLE recorrido_punto (
    ruta_id     INTEGER      NOT NULL,
    orden       SMALLINT     NOT NULL CHECK (orden > 0),
    latitud     NUMERIC(9,6) NOT NULL,
    longitud    NUMERIC(9,6) NOT NULL,
    PRIMARY KEY (ruta_id, orden),
    CONSTRAINT fk_recorrido_ruta FOREIGN KEY (ruta_id) REFERENCES ruta (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
--  Operación
-- ---------------------------------------------------------------------

CREATE TABLE viaje (
    id                  INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chofer_id           INTEGER      NOT NULL,
    vehiculo_id         INTEGER      NOT NULL,
    ruta_id             INTEGER      NOT NULL,
    inicio              TIMESTAMPTZ  NOT NULL,
    fin                 TIMESTAMPTZ  NULL,
    pasajeros_salida    SMALLINT     NULL CHECK (pasajeros_salida >= 0),
    estado              VARCHAR(15)  NOT NULL DEFAULT 'en_curso',
    CONSTRAINT fk_viaje_chofer   FOREIGN KEY (chofer_id)   REFERENCES chofer (id),
    CONSTRAINT fk_viaje_vehiculo FOREIGN KEY (vehiculo_id) REFERENCES vehiculo (id),
    CONSTRAINT fk_viaje_ruta     FOREIGN KEY (ruta_id)     REFERENCES ruta (id),
    CONSTRAINT fk_viaje_estado   FOREIGN KEY (estado)      REFERENCES estado_viaje (clave) ON UPDATE CASCADE
);
CREATE INDEX ix_viaje_chofer ON viaje (chofer_id, inicio);
CREATE INDEX ix_viaje_vehiculo ON viaje (vehiculo_id);
CREATE INDEX ix_viaje_ruta ON viaje (ruta_id);
CREATE INDEX ix_viaje_estado ON viaje (estado);
COMMENT ON COLUMN viaje.pasajeros_salida IS 'NULL si el chofer no lo registró';

CREATE TABLE reporte_accidente (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruta_id         INTEGER      NOT NULL,
    usuario_id      INTEGER      NULL,
    descripcion     VARCHAR(500) NOT NULL,
    contacto        VARCHAR(120) NULL,
    latitud         NUMERIC(9,6) NULL,
    longitud        NUMERIC(9,6) NULL,
    estado          VARCHAR(15)  NOT NULL DEFAULT 'nuevo',
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    revisado_por    INTEGER      NULL,
    revisado_en     TIMESTAMPTZ  NULL,
    CONSTRAINT fk_reporte_ruta    FOREIGN KEY (ruta_id)      REFERENCES ruta (id),
    CONSTRAINT fk_reporte_usuario FOREIGN KEY (usuario_id)   REFERENCES usuario (id) ON DELETE SET NULL,
    CONSTRAINT fk_reporte_revisor FOREIGN KEY (revisado_por) REFERENCES usuario (id) ON DELETE SET NULL,
    CONSTRAINT fk_reporte_estado  FOREIGN KEY (estado)       REFERENCES estado_reporte (clave) ON UPDATE CASCADE
);
CREATE INDEX ix_reporte_ruta ON reporte_accidente (ruta_id);
CREATE INDEX ix_reporte_usuario ON reporte_accidente (usuario_id);
CREATE INDEX ix_reporte_revisor ON reporte_accidente (revisado_por);
CREATE INDEX ix_reporte_estado ON reporte_accidente (estado);
COMMENT ON COLUMN reporte_accidente.usuario_id IS 'Quién reportó (NULL si fue anónimo)';

-- Fallas o detalles de cada unidad (llanta ponchada, clima descompuesto…) y su atención.
CREATE TABLE falla_vehiculo (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id     INTEGER      NOT NULL,
    tipo            VARCHAR(20)  NOT NULL,
    descripcion     VARCHAR(500) NULL,
    impide_circular SMALLINT     NOT NULL DEFAULT 0 CHECK (impide_circular IN (0, 1)),
    estado          VARCHAR(15)  NOT NULL DEFAULT 'pendiente',
    reportado_por   INTEGER      NULL,
    viaje_id        INTEGER      NULL,
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atendido_por    INTEGER      NULL,
    nota_solucion   VARCHAR(255) NULL,
    resuelto_en     TIMESTAMPTZ  NULL,
    CONSTRAINT fk_falla_vehiculo FOREIGN KEY (vehiculo_id)   REFERENCES vehiculo (id),
    CONSTRAINT fk_falla_tipo     FOREIGN KEY (tipo)          REFERENCES tipo_falla (clave) ON UPDATE CASCADE,
    CONSTRAINT fk_falla_estado   FOREIGN KEY (estado)        REFERENCES estado_falla (clave) ON UPDATE CASCADE,
    CONSTRAINT fk_falla_reporta  FOREIGN KEY (reportado_por) REFERENCES usuario (id) ON DELETE SET NULL,
    CONSTRAINT fk_falla_viaje    FOREIGN KEY (viaje_id)      REFERENCES viaje (id)   ON DELETE SET NULL,
    CONSTRAINT fk_falla_atiende  FOREIGN KEY (atendido_por)  REFERENCES usuario (id) ON DELETE SET NULL
);
CREATE INDEX ix_falla_vehiculo ON falla_vehiculo (vehiculo_id, estado);
CREATE INDEX ix_falla_tipo ON falla_vehiculo (tipo);
CREATE INDEX ix_falla_estado ON falla_vehiculo (estado);
CREATE INDEX ix_falla_reporta ON falla_vehiculo (reportado_por);
CREATE INDEX ix_falla_viaje ON falla_vehiculo (viaje_id);
CREATE INDEX ix_falla_atiende ON falla_vehiculo (atendido_por);
COMMENT ON COLUMN falla_vehiculo.impide_circular IS '1 = la unidad no puede salir a ruta hasta resolver la falla';
COMMENT ON COLUMN falla_vehiculo.viaje_id IS 'Viaje en el que se detectó (si la unidad estaba en ruta)';

-- Rutas y paradas que consultó cada pasajero (una de las dos puede ser NULL).
CREATE TABLE historial_consulta (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      INTEGER      NOT NULL,
    ruta_id         INTEGER      NULL,
    parada_id       INTEGER      NULL,
    consultado_en   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_historial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_historial_ruta    FOREIGN KEY (ruta_id)    REFERENCES ruta (id)    ON DELETE CASCADE,
    CONSTRAINT fk_historial_parada  FOREIGN KEY (parada_id)  REFERENCES parada (id)  ON DELETE CASCADE
);
CREATE INDEX ix_historial_usuario ON historial_consulta (usuario_id, consultado_en);
CREATE INDEX ix_historial_ruta ON historial_consulta (ruta_id);
CREATE INDEX ix_historial_parada ON historial_consulta (parada_id);

-- Sesiones de la API (inicio de sesión), para que funcionen aunque el sitio corra en varios servidores (Vercel).
CREATE TABLE sesion (
    id          VARCHAR(128) NOT NULL PRIMARY KEY,
    datos       TEXT         NOT NULL,
    expira      BIGINT       NOT NULL
);
CREATE INDEX ix_sesion_expira ON sesion (expira);
COMMENT ON COLUMN sesion.expira IS 'Fecha de vencimiento (segundos Unix)';

-- ---------------------------------------------------------------------
--  Vistas de consulta
-- ---------------------------------------------------------------------

CREATE VIEW vista_rutas WITH (security_invoker = true) AS
SELECT r.id, l.nombre AS linea, r.codigo, r.nombre, s.nombre AS sentido, r.origen, r.destino,
       r.tarifa, e.nombre AS estado_servicio, r.activa,
       (SELECT COUNT(*) FROM ruta_parada rp WHERE rp.ruta_id = r.id) AS total_paradas
FROM ruta r
JOIN linea_transporte l ON l.id = r.linea_id
JOIN sentido_ruta s ON s.clave = r.sentido
JOIN estado_servicio e ON e.clave = r.estado_servicio;

CREATE VIEW vista_viajes_en_curso WITH (security_invoker = true) AS
SELECT v.id, u.nombre AS chofer, ve.numero_unidad, ve.placa, r.codigo AS ruta, r.nombre AS nombre_ruta,
       v.inicio, v.pasajeros_salida
FROM viaje v
JOIN chofer c ON c.id = v.chofer_id
JOIN usuario u ON u.id = c.usuario_id
JOIN vehiculo ve ON ve.id = v.vehiculo_id
JOIN ruta r ON r.id = v.ruta_id
WHERE v.estado = 'en_curso';

CREATE VIEW vista_fallas_abiertas WITH (security_invoker = true) AS
SELECT f.id, l.nombre AS linea, ve.numero_unidad, ve.placa, t.nombre AS tipo, f.descripcion,
       f.impide_circular, e.nombre AS estado, u.nombre AS reportado_por, f.creado_en
FROM falla_vehiculo f
JOIN vehiculo ve ON ve.id = f.vehiculo_id
JOIN linea_transporte l ON l.id = ve.linea_id
JOIN tipo_falla t ON t.clave = f.tipo
JOIN estado_falla e ON e.clave = f.estado
LEFT JOIN usuario u ON u.id = f.reportado_por
WHERE f.estado <> 'resuelta';

-- ---------------------------------------------------------------------
--  Seguridad: solo la API (usuario postgres) lee y escribe. La API pública de Supabase (anon / authenticated)
--  no puede ver contraseñas, sesiones ni ningún otro dato.
-- ---------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
